# fly.toml app configuration file generated for greengrowth on 2025-07-18T13:04:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'greengrowth'
primary_region = 'ord'

[build]


[processes]
  web    = "uvicorn main:app --host 0.0.0.0 --port 10000"
  worker = "python taxcalculation.py"


[http_service]
  internal_port      = 10000
  force_https        = true
  auto_stop_machines = "off"    # “off” means never stop when idle
  auto_start_machines= true
  min_machines_running = 1      # always keep one web VM live

  [http_service.concurrency]
    type       = "requests"
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
